AllCops:
  NewCops: enable
  Exclude:
    - "lib/slimer/web/csfr_protection.rb"

Metrics/AbcSize:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*_test.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
