require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
AllCops:
  NewCops: enable
  Exclude:
    - "lib/slimer/web/csfr_protection.rb"
    - "**/.ruby-version"
    - "examples/**/*"
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Exclude:
    - "test/**/*_test.rb"

Metrics/MethodLength:
  Exclude:
    - "test/**/*_test.rb"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
