name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - review_requested
      - ready_for_review

jobs:
  lint:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Lint Check for Latest ruby
        run: bundle exec rake rubocop
